import { ParkingSpot, SpotStatus } from '../../models/ParkingSpot';
import { VehicleSize } from '../../models/Vehicle';

/**
 * Factory for creating ParkingSpot instances
 */
export class ParkingSpotFactory {
  /**
   * Create a parking spot
   * Note: ID will be generated by the repository (MongoDB ObjectId)
   * This factory creates a temporary ID that gets replaced on save
   */
  static createSpot(
    floor: number,
    spotNumber: string,
    size: VehicleSize,
    status: SpotStatus = SpotStatus.AVAILABLE
  ): ParkingSpot {
    // Generate temporary ID (will be replaced by repository)
    const tempId = this.generateTempId();
    return new ParkingSpot(tempId, floor, spotNumber, size, status);
  }

  /**
   * Generate a temporary ID (will be replaced by repository with proper ID)
   */
  private static generateTempId(): string {
    if (typeof crypto !== 'undefined' && crypto.randomUUID) {
      return crypto.randomUUID();
    }
    // Fallback for older Node.js
    return `temp-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
  }

  /**
   * Create a small spot (for motorcycles)
   */
  static createSmallSpot(floor: number, spotNumber: string): ParkingSpot {
    return this.createSpot(floor, spotNumber, VehicleSize.SMALL);
  }

  /**
   * Create a medium spot (for cars)
   */
  static createMediumSpot(floor: number, spotNumber: string): ParkingSpot {
    return this.createSpot(floor, spotNumber, VehicleSize.MEDIUM);
  }

  /**
   * Create a large spot (for buses)
   */
  static createLargeSpot(floor: number, spotNumber: string): ParkingSpot {
    return this.createSpot(floor, spotNumber, VehicleSize.LARGE);
  }

  /**
   * Create multiple spots in bulk
   */
  static createSpotsForFloor(
    floor: number,
    smallSpots: number,
    mediumSpots: number,
    largeSpots: number
  ): ParkingSpot[] {
    const spots: ParkingSpot[] = [];
    let spotNumber = 1;

    // Create small spots
    for (let i = 0; i < smallSpots; i++) {
      spots.push(this.createSmallSpot(floor, `S${spotNumber++}`));
    }

    // Create medium spots
    for (let i = 0; i < mediumSpots; i++) {
      spots.push(this.createMediumSpot(floor, `M${spotNumber++}`));
    }

    // Create large spots
    for (let i = 0; i < largeSpots; i++) {
      spots.push(this.createLargeSpot(floor, `L${spotNumber++}`));
    }

    return spots;
  }

}
