import { Vehicle, VehicleType, VehicleSize } from '../../models/Vehicle';

/**
 * Factory for creating Vehicle instances
 */
export class VehicleFactory {
  private static vehicleIdCounter: number = 1;

  /**
   * Create a vehicle based on type
   * Note: ID will be generated by the repository (MongoDB ObjectId or proper UUID)
   * This factory creates a temporary ID that gets replaced on save
   */
  static createVehicle(
    licensePlate: string,
    type: VehicleType,
    entryTime?: Date
  ): Vehicle {
    // Generate proper UUID instead of sequential counter
    const tempId = this.generateTempId();
    const size = this.getVehicleSize(type);

    return new Vehicle(tempId, licensePlate, type, size, entryTime);
  }

  /**
   * Generate a temporary ID (will be replaced by repository with proper ID)
   */
  private static generateTempId(): string {
    if (typeof crypto !== 'undefined' && crypto.randomUUID) {
      return crypto.randomUUID();
    }
    // Fallback for older Node.js
    return `temp-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
  }

  /**
   * Create a motorcycle
   */
  static createMotorcycle(licensePlate: string, entryTime?: Date): Vehicle {
    return this.createVehicle(licensePlate, VehicleType.MOTORCYCLE, entryTime);
  }

  /**
   * Create a car
   */
  static createCar(licensePlate: string, entryTime?: Date): Vehicle {
    return this.createVehicle(licensePlate, VehicleType.CAR, entryTime);
  }

  /**
   * Create a bus
   */
  static createBus(licensePlate: string, entryTime?: Date): Vehicle {
    return this.createVehicle(licensePlate, VehicleType.BUS, entryTime);
  }

  /**
   * Get vehicle size based on type
   */
  private static getVehicleSize(type: VehicleType): VehicleSize {
    const sizeMap: Record<VehicleType, VehicleSize> = {
      [VehicleType.MOTORCYCLE]: VehicleSize.SMALL,
      [VehicleType.CAR]: VehicleSize.MEDIUM,
      [VehicleType.BUS]: VehicleSize.LARGE
    };

    return sizeMap[type];
  }

}
